// Demo/seed content for the unified content engine. All data is invented for
// demonstration purposes (see /docs — no real UCL data is used).
export const CONTENT_SEED = [
  {
    title: 'Semester 1 Exam Timetable Released',
    description: 'The final exam timetable for Semester 1 has been published. Check your faculty portal for your personal schedule.',
    category: 'ANNOUNCEMENT',
    audience: 'EVERYONE',
    createdBy_display: 'Academic Registry',
  },
  {
    title: 'Computing Faculty: Lab Access Hours Extended',
    description: 'Lab access for Faculty of Computing students is now extended to 9pm on weekdays for the exam period.',
    category: 'ANNOUNCEMENT',
    audience: 'FACULTY',
    faculty: 'Faculty of Computing',
    createdBy_display: 'Faculty of Computing Office',
  },
  {
    title: 'Year 1 Orientation Follow-up Session',
    description: 'A follow-up orientation session for all first-year students will cover library access, IT accounts, and campus navigation.',
    category: 'ANNOUNCEMENT',
    audience: 'YEAR_GROUP',
    yearGroup: 1,
    createdBy_display: 'Student Affairs',
  },
  {
    title: 'Campus Power Maintenance — Block C Closed Tomorrow',
    description: 'Scheduled electrical maintenance means Block C will be closed from 8am–1pm tomorrow. Classes relocated to Block A.',
    category: 'SCHEDULE_CHANGE',
    audience: 'EVERYONE',
    isEmergency: true,
    createdBy_display: 'Facilities Management',
  },
  {
    title: 'Severe Weather Advisory',
    description: 'Heavy rain warning issued for the region. Evening classes after 6pm are suspended today. Stay safe and check announcements before traveling to campus.',
    category: 'EMERGENCY',
    audience: 'EVERYONE',
    isEmergency: true,
    createdBy_display: 'Campus Security',
  },
  {
    title: 'AI & Data Hackathon Showcase',
    description: 'Join us for a showcase of student hackathon projects, including live demos and a panel of industry judges.',
    category: 'EVENT',
    audience: 'EVERYONE',
    eventDate: daysFromNow(4),
    startTime: '14:00:00',
    endTime: '17:00:00',
    location: 'Main Auditorium',
    contact: 'events@ucl.lk',
    createdBy_display: 'Computing Society',
  },
  {
    title: 'Inter-Faculty Football Tournament',
    description: 'Cheer on your faculty team in the annual inter-faculty football tournament.',
    category: 'EVENT',
    audience: 'EVERYONE',
    eventDate: daysFromNow(9),
    startTime: '09:00:00',
    endTime: '16:00:00',
    location: 'Sports Grounds',
    createdBy_display: 'Sports Office',
  },
  {
    title: 'Business Faculty Career Fair',
    description: 'Meet recruiters from leading companies looking to hire finance, marketing and management graduates.',
    category: 'EVENT',
    audience: 'FACULTY',
    faculty: 'Faculty of Business',
    eventDate: daysFromNow(14),
    startTime: '10:00:00',
    endTime: '15:00:00',
    location: 'Business Faculty Hall',
    createdBy_display: 'Faculty of Business Office',
  },
  {
    title: 'Robotics Club',
    description: 'Build and compete with autonomous robots. Weekly workshops every Wednesday evening. No experience required.',
    category: 'SOCIETY',
    audience: 'EVERYONE',
    contact: 'robotics.club@ucl.lk',
    createdBy_display: 'Robotics Club',
  },
  {
    title: 'Photography Society',
    description: 'Capture campus life, learn editing techniques, and take part in our annual exhibition.',
    category: 'SOCIETY',
    audience: 'EVERYONE',
    contact: 'photosoc@ucl.lk',
    createdBy_display: 'Photography Society',
  },
  {
    title: 'Toastmasters Public Speaking Club',
    description: 'Improve your public speaking and leadership skills in a supportive peer environment.',
    category: 'SOCIETY',
    audience: 'EVERYONE',
    contact: 'toastmasters@ucl.lk',
    createdBy_display: 'Toastmasters Club',
  },
  {
    title: 'Add/Drop Period',
    description: 'Module add/drop requests are open. Submit changes through the academic portal before the deadline.',
    category: 'ACADEMIC_CALENDAR',
    audience: 'EVERYONE',
    eventDate: daysFromNow(2),
    createdBy_display: 'Academic Registry',
  },
  {
    title: 'Semester 2 Begins',
    description: 'Semester 2 lectures commence for all faculties.',
    category: 'ACADEMIC_CALENDAR',
    audience: 'EVERYONE',
    eventDate: daysFromNow(45),
    createdBy_display: 'Academic Registry',
  },
  {
    title: 'Final Exam Period',
    description: 'End-of-semester examinations for all faculties.',
    category: 'ACADEMIC_CALENDAR',
    audience: 'EVERYONE',
    eventDate: daysFromNow(60),
    createdBy_display: 'Academic Registry',
  },
  {
    title: 'New Student Survival Guide',
    description: 'Everything a first-year student needs to know: getting your student ID, IT account setup, finding your classrooms, and where to get help.',
    category: 'ONBOARDING',
    audience: 'YEAR_GROUP',
    yearGroup: 1,
    createdBy_display: 'Student Affairs',
  },
  {
    title: 'Beach Cleanup Volunteering Day',
    description: 'Join fellow students for a community beach cleanup. Certificates of participation provided.',
    category: 'VOLUNTEERING',
    audience: 'EVERYONE',
    eventDate: daysFromNow(11),
    location: 'Mount Lavinia Beach',
    createdBy_display: 'Community Engagement Office',
  },
  {
    title: 'Alumni Mentorship Circle — Applications Open',
    description: 'Get paired with a UCL alumni mentor in your field for a semester of guidance and networking.',
    category: 'ALUMNI',
    audience: 'EVERYONE',
    createdBy_display: 'Alumni Relations',
  },
  {
    title: 'Software Engineer Intern — TechNova Lanka',
    description: '6-month internship for penultimate/final-year Computing students. Apply via the careers office.',
    category: 'JOB',
    audience: 'FACULTY',
    faculty: 'Faculty of Computing',
    contact: 'careers@ucl.lk',
    createdBy_display: 'Careers Office',
  },
  {
    title: 'Part-Time Campus Library Assistant',
    description: 'Paid part-time role assisting with circulation desk duties, 10 hours/week.',
    category: 'JOB',
    audience: 'EVERYONE',
    contact: 'library@ucl.lk',
    createdBy_display: 'Library Services',
  },
  {
    title: 'Merit Scholarship Applications Open',
    description: 'Students with a GPA above 3.7 may apply for the Semester 2 merit scholarship. Deadline in two weeks.',
    category: 'FINANCIAL_SUPPORT',
    audience: 'EVERYONE',
    createdBy_display: 'Financial Aid Office',
  },
  {
    title: 'Free Counselling Sessions',
    description: 'Confidential one-on-one counselling is available to all students. Book a slot through the wellbeing office.',
    category: 'WELLBEING',
    audience: 'EVERYONE',
    contact: 'wellbeing@ucl.lk',
    createdBy_display: 'Student Wellbeing Centre',
  },
  {
    title: 'Password Reset & VPN Setup Guide',
    description: 'Step-by-step instructions for resetting your student portal password and configuring the campus VPN.',
    category: 'IT_SUPPORT',
    audience: 'EVERYONE',
    contact: 'ithelpdesk@ucl.lk',
    createdBy_display: 'IT Helpdesk',
  },
  {
    title: 'Library Extended Hours for Exam Season',
    description: 'The main library will be open 24 hours during the two weeks before final exams.',
    category: 'LIBRARY',
    audience: 'EVERYONE',
    createdBy_display: 'Library Services',
  },
  {
    title: 'Cafeteria Weekly Menu',
    description: 'This week\'s cafeteria menu includes rice & curry, noodles, and a vegetarian option daily. Open 7:30am–7pm.',
    category: 'DINING',
    audience: 'EVERYONE',
    createdBy_display: 'Campus Dining Services',
  },
  {
    title: 'Printing Credits & Rates',
    description: 'Printing is available at the library and IT lab. Black & white LKR 5/page, colour LKR 20/page. Top up credits online.',
    category: 'PRINTING',
    audience: 'EVERYONE',
    createdBy_display: 'IT Helpdesk',
  },
  {
    title: 'Second-Hand Textbooks — Data Structures & Algorithms',
    description: 'Selling a lightly used copy of the year 2 Data Structures textbook. Message via contact info.',
    category: 'TEXTBOOK',
    audience: 'FACULTY',
    faculty: 'Faculty of Computing',
    contact: 'student.seller@ucl.lk',
    createdBy_display: 'Student Marketplace',
  },
  {
    title: 'Guest Lecture: Careers in Cybersecurity',
    description: 'Industry expert from a leading security firm shares insights on breaking into cybersecurity roles.',
    category: 'GUEST_LECTURE',
    audience: 'EVERYONE',
    eventDate: daysFromNow(7),
    startTime: '13:00:00',
    endTime: '14:30:00',
    location: 'Lecture Hall 2',
    createdBy_display: 'Faculty of Computing Office',
  },
  {
    title: 'Gym & Fitness Centre Access',
    description: 'The campus gym is open to all students free of charge. Court bookings for badminton and basketball available at the sports office.',
    category: 'SPORTS',
    audience: 'EVERYONE',
    createdBy_display: 'Sports Office',
  },
  {
    title: 'Last Semester\'s Cultural Night Highlights',
    description: 'Relive the best moments from last semester\'s cultural night, featuring performances from every faculty.',
    category: 'STUDENT_LIFE',
    audience: 'EVERYONE',
    createdBy_display: 'Student Affairs',
  },
  {
    title: 'How do I reset my student portal password?',
    description: 'Go to portal.ucl.lk/reset and use your student email. If you don\'t receive a reset link within 10 minutes, contact the IT Helpdesk.',
    category: 'FAQ',
    audience: 'EVERYONE',
  },
  {
    title: 'How do I request an official transcript?',
    description: 'Submit a transcript request form at the Academic Registry office or via the student portal under "Documents". Processing takes 3–5 working days.',
    category: 'FAQ',
    audience: 'EVERYONE',
  },
  {
    title: 'Where can I find the academic calendar?',
    description: 'The full academic calendar is available under the Academic Calendar section of UCL ONE and on the registry noticeboard.',
    category: 'FAQ',
    audience: 'EVERYONE',
  },
  {
    title: 'Dr. Amara Perera — Head of Computing',
    description: 'Faculty of Computing. Office: Block A, Room 204. Email: a.perera@ucl.lk. Office hours: Tue/Thu 2–4pm.',
    category: 'STAFF_DIRECTORY',
    audience: 'EVERYONE',
  },
  {
    title: 'Student Affairs Office',
    description: 'General student support, ID cards, and administrative queries. Block B, Ground Floor. Email: studentaffairs@ucl.lk.',
    category: 'STAFF_DIRECTORY',
    audience: 'EVERYONE',
  },
];

function daysFromNow(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}
